#!/usr/bin/env bash

set -eux -o pipefail

here=$(cd "$(dirname "$0")" && pwd)
image=$("${here}/image-name")

"${here}/build"

docker run \
  --volume /:/host \
  --tmpfs /tmp \
  --privileged \
  -it \
  --rm \
  "$image" bash
